------------------------------------------------------------------------------------------------------------------------------------------------------

-- fiddle with / replace / stretch out vanilla techs
-- no need to specify chains as prereqs, no need to specify prereqs that provide ingredients - conceptual prereqs only

add_new_minimal_tech("automated-rail-transportation", "automated-rail-transportation", true, {"train-stop","rail-signal","rail-chain-signal"}, {"railway"}) 
add_new_minimal_tech("battery", "charged-battery", false, {"battery","charged-battery","battery-discharge-equipment","iron-battery-charger","iron-battery-discharger"}, {}) 
add_new_minimal_tech("engine", "engine-unit", false, {"engine-unit"}, {})
add_new_minimal_tech("electric-engine", "electric-engine-unit", false, {"electric-engine-unit"}, {"engine"})
add_new_minimal_tech("laser", "laser", false, {"laser"}, {}) 
add_new_minimal_tech("military", "military", true, {"submachine-gun","iron-magazine","iron-cartridge"}, nil) 
add_new_minimal_tech("military-2", "military", true, {"grenade","steel-magazine","steel-cartridge"}, {}) 
add_new_minimal_tech("military-3", "military", true, {"combat-shotgun","titanium-magazine","titanium-cartridge","poison-capsule","slowdown-capsule"}, {}) 
add_new_minimal_tech("military-4", "military", true, {"uranium-magazine","uranium-cartridge","uranium-cannon-shell","explosive-uranium-cannon-shell","cluster-grenade"}, {}) 
add_new_minimal_tech("personal-roboport-equipment", "personal-roboport-equipment", true, {"construction-robot","personal-roboport-equipment"}, {"modular-armor"})
add_new_minimal_tech("plastics", "plastics", true, {"plastic-fluid","plastic-bar"}, {}) 
add_new_minimal_tech("robotics", "roboport", false, {"roboport"}, {"deadlock-robotower"})
add_new_minimal_tech("sulfur-processing", "sulfuric-acid", false, {"sulfur","sulfuric-acid","rubber-vulcanised"}, {"oil-processing"}) 
add_new_minimal_tech("turrets", "scattergun-turret", false, {"scattergun-turret"}, {}) 
add_new_minimal_tech("laser-turrets", "laser-turret", false, {"laser-turret"}, {"military-2"}) 
add_new_minimal_tech("oil-processing","oil-processing",true, {"oil-refinery","pumpjack","chemical-plant","flare-stack","basic-oil-processing","heavy-oil-cracking","light-oil-cracking","solid-fuel-from-heavy-oil","solid-fuel-from-light-oil","solid-fuel-from-petroleum-gas"}, {"fluid-handling"})
add_new_minimal_tech("advanced-oil-processing","oil-processing",true, {"advanced-heavy-oil-cracking","advanced-light-oil-cracking"}, {"deadlock-washing-1"}) -- explicit prereq because enrichment
add_new_minimal_tech("electric-energy-distribution-1","electric-energy-distribution",true, {"medium-electric-pole","big-electric-pole","steel-cable"}, {"battery"})
add_new_minimal_tech("electric-energy-distribution-2","electric-energy-distribution",true, {"substation","junction-box","steel-ring"}, {})

remove_unlock_from_tech("automation", "long-handed-inserter")
remove_unlock_from_tech("kovarex-enrichment-process", "nuclear-fuel")
remove_all_barrels_from_tech("fluid-handling")
add_unlock_to_tech("fluid-handling", "small-tank")
add_unlock_to_tech("modular-armor", "iron-burner-generator-equipment")

replace_tech_icon("automation","assembler1")
replace_tech_icon("automation-2","assembler2")
replace_tech_icon("automation-3","assembler3")
replace_tech_icon("rocket-fuel","rocket-fuel")

------------------------------------------------------------------------------------------------------------------------------------------------------

-- add conceptual prerequisites

add_prereq_to_tech("advanced-oil-processing", "oil-processing")
add_prereq_to_tech("artillery", "deadlock-photon-turret")
add_prereq_to_tech("artillery-shell-range-1", "artillery")
add_prereq_to_tech("artillery-shell-speed-1", "artillery")
add_prereq_to_tech("atomic-bomb", "nuclear-power")
add_prereq_to_tech("auto-character-logistic-trash-slots", "character-logistic-trash-slots-1")
add_prereq_to_tech("automated-rail-transportation", "railway")
add_prereq_to_tech("battery-equipment", "modular-armor")
add_prereq_to_tech("battery-mk2-equipment", "battery-equipment")
add_prereq_to_tech("belt-immunity-equipment", "modular-armor")
add_prereq_to_tech("braking-force-1", "railway")
add_prereq_to_tech("character-logistic-slots-1", "deadlock-robotower")
add_prereq_to_tech("character-logistic-trash-slots-1", "deadlock-robotower")
add_prereq_to_tech("chemical-science-pack", "deadlock-research-1")
add_prereq_to_tech("chemical-science-pack", "sulfur-processing")
add_prereq_to_tech("chemical-science-pack", "lubricant")
add_prereq_to_tech("coal-liquefaction", "advanced-oil-processing")
add_prereq_to_tech("combat-robotics", "military-2")
add_prereq_to_tech("combat-robotics-2", "military-3")
add_prereq_to_tech("combat-robotics-3", "deadlock-arc-turret")
add_prereq_to_tech("discharge-defense-equipment", "power-armor")
add_prereq_to_tech("discharge-defense-equipment", "military-4")
add_prereq_to_tech("discharge-defense-equipment", "deadlock-arc-turret")
add_prereq_to_tech("effect-transmission", "deadlock-modules-3")
add_prereq_to_tech("electric-engine", "battery")
add_prereq_to_tech("energy-shield-equipment", "power-armor")
add_prereq_to_tech("energy-shield-mk2-equipment", "energy-shield-equipment")
add_prereq_to_tech("energy-shield-mk2-equipment", "power-armor-mk2")
add_prereq_to_tech("energy-weapons-damage-1", "laser-turrets")
add_prereq_to_tech("exoskeleton-equipment", "modular-armor")
add_prereq_to_tech("flamethrower", "military-2")
add_prereq_to_tech("fluid-handling", "deadlock-steam-power")
add_prereq_to_tech("fluid-wagon", "railway")
add_prereq_to_tech("fluid-wagon", "fluid-handling")
add_prereq_to_tech("follower-robot-count-1", "combat-robotics")
add_prereq_to_tech("follower-robot-count-4", "combat-robotics-2")
add_prereq_to_tech("follower-robot-count-7", "combat-robotics-3")
add_prereq_to_tech("fusion-reactor-equipment", "power-armor-mk2")
add_prereq_to_tech("fusion-reactor-equipment", "nuclear-power")
add_prereq_to_tech("inserter-capacity-bonus-1", "deadlock-inserters-3")
add_prereq_to_tech("kovarex-enrichment-process", "uranium-processing")
add_prereq_to_tech("land-mine", "military-2")
add_prereq_to_tech("logistic-system", "robotics")
add_prereq_to_tech("military-science-pack", "military")
add_prereq_to_tech("military-science-pack", "deadlock-research-1")
add_prereq_to_tech("military-2", "explosives")
add_prereq_to_tech("modular-armor", "heavy-armor")
add_prereq_to_tech("modular-armor", "deadlock-modules-1")
add_prereq_to_tech("night-vision-equipment", "modular-armor")
add_prereq_to_tech("night-vision-equipment", "optics")
add_prereq_to_tech("nuclear-fuel-reprocessing", "nuclear-power")
add_prereq_to_tech("nuclear-power", "uranium-processing")
add_prereq_to_tech("personal-laser-defense-equipment", "laser-turrets")
add_prereq_to_tech("personal-laser-defense-equipment", "military-4")
add_prereq_to_tech("personal-laser-defense-equipment", "power-armor-mk2")
add_prereq_to_tech("personal-roboport-equipment", "modular-armor")
add_prereq_to_tech("personal-roboport-mk2-equipment", "personal-roboport-equipment")
add_prereq_to_tech("physical-projectile-damage-4", "military-2")
add_prereq_to_tech("physical-projectile-damage-5", "deadlock-minigun-turret")
add_prereq_to_tech("power-armor", "modular-armor")
add_prereq_to_tech("power-armor-mk2", "power-armor")
add_prereq_to_tech("rail-signals", "railway")
add_prereq_to_tech("refined-flammables-1", "flamethrower")
add_prereq_to_tech("research-speed-1", "deadlock-research-1")
add_prereq_to_tech("rocket-control-unit", "rocket-fuel")
add_prereq_to_tech("rocketry", "military-2")
add_prereq_to_tech("solar-panel-equipment", "modular-armor")
add_prereq_to_tech("space-science-pack", "rocket-silo")
add_prereq_to_tech("stronger-explosives-1", "explosives")
add_prereq_to_tech("stronger-explosives-1", "military-2")
add_prereq_to_tech("stronger-explosives-2", "land-mine")
add_prereq_to_tech("stronger-explosives-3","rocketry")
add_prereq_to_tech("stronger-explosives-3","tanks")
add_prereq_to_tech("tanks", "automobilism")
add_prereq_to_tech("tanks", "deadlock-minigun")
add_prereq_to_tech("weapon-shooting-speed-4", "military-2")
add_prereq_to_tech("worker-robots-speed-1", "deadlock-robotower")
add_prereq_to_tech("worker-robots-storage-1", "robotics")

------------------------------------------------------------------------------------------------------------------------------------------------------
